#!/bin/bash

#Install zabbix server
#author by djshi2
#ip.list file need have ip user and password

ip=$1

checkos(){
! uname -a | grep "centos7" > /dev/null && echo "error: Your operating system is not CentOS7 on $ip" && exit 1
}

setfirewalld(){
[ "`getenforce`" != "Disabled" ] && setenforce 0 && sed -i 's/SELINUX=enforcing/SELINUX=disabled/' /etc/selinux/config
! systemctl status firewalld | grep "dead" > /dev/null && systemctl stop firewalld && systemctl disable firewalld
}

zabbix_server_install(){
rpm -ivh http://repo.zabbix.com/zabbix/3.4/rhel/7/x86_64/zabbix-release-3.4-2.el7.noarch.rpm && yum install -y zabbix-server-mysql zabbix-web-mysql
! rpm -qa|grep "zabbix" > /dev/null && echo "error: Installation of zabbix_server failed on $ip" && exit 1
}

mariadb_server_install(){
yum install -y mariadb-server
! rpm -qa|grep "mariadb" > /dev/null && echo "error: Installation of mariadb failed on $ip" && eixt 1

systemctl start mariadb && systemctl enable mariadb
! systemctl status mariadb | grep "active (running)" > /dev/null && echo "error: Failed to start mariadb on $ip" && exit 1

mysql << EOF
create database zabbix character set utf8 collate utf8_bin;
grant all privileges on zabbix.* to zabbix@'%' identified by 'zabbix';
grant all privileges on zabbix.* to zabbix@localhost identified by 'zabbix';
grant all privileges on zabbix.* to zabbix@localhost.localdomain identified by 'zabbix';
EOF

cd /usr/share/doc/zabbix-server-mysql-3.4.12/ && zcat create.sql.gz |mysql -uroot zabbix
}

zabbix_server_config(){
sed -i "s/# DBHost=localhost/DBHost=localhost/g" /etc/zabbix/zabbix_server.conf && sed -i "s/# DBPassword=/DBPassword=zabbix/g" /etc/zabbix/zabbix_server.conf

systemctl start zabbix-server && systemctl enable zabbix-server
! systemctl status zabbix-server | grep "active (running)" > /dev/null && echo "error: Failed to start zabbix-server on $ip" && exit 1

sed -i "s/# php_value date.timezone Europe\/Riga/php_value date.timezone Asia\/Shanghai/g" /etc/httpd/conf.d/zabbix.conf

systemctl start httpd && systemctl enable httpd
! systemctl status httpd | grep "active (running)" > /dev/null && echo "error: Failed to start httpd on $ip" && exit 1
}


zabbix_agentd(){
yum install -y zabbix-agent
! rpm -qa|grep "zabbix-agent" > /dev/null && echo "error: Installation of zabbix_agent failed on $ip" && eixt 1

systemctl start zabbix-agent && systemctl enable zabbix-agent
! systemctl status zabbix-agent | grep "active (running)" > /dev/null && echo "error: Failed to start zabbix-agent on $ip" && exit 1
}


checkos
setfirewalld
zabbix_server_install
mariadb_server_install
zabbix_server_config
zabbix_agentd
